# define paths
data:
    SOURCE_DATA_PATH: "source_data/partiju_skirotava.json"
    TOPIC_MAPPING_PATH: "source_data/topic_mapping.xlsx"
    

outputs:
    3D_PLOT_PATH : "outputs/pca_projection_3d.html"
    OUTPUT_FOLDER_PATH : "outputs"

colours:
    jauna-vienotiba: "#7ebc5e"
    nacionala-apvieniba: "#e4b919"
    latvija-pirmaja-vieta: "#9c454e"
    progresivie: "#d45c4f"
    zalo-un-zemnieku-savieniba: "#319957"
    apvienotais-saraksts: "#e6991c"
    suverena-vara: "#7274a7"
    stabilitatei: "#e07d14"
    saskana: "#e5000b"
    attistibai-par: "#ebdf17"
    latvijas-krievu-savieniba: "#e631c2"
    katram-un-katrai: "#2aa28f"
    republika: "#b3b3b3"
    konservativie: "#404464"
